#------------------------------------------------------------------------------------------------
#-- Table HOTEL_CHAINS
#------------------------------------------------------------------------------------------------
DROP TABLE IF EXISTS `HOTEL_CHAINS`;

CREATE TABLE IF NOT EXISTS `HOTEL_CHAINS`(
HOTEL_CHAIN_ID INT NOT NULL,
HOTEL_CHAIN_NAME VARCHAR(100) NOT NULL,
PRIMARY KEY (HOTEL_CHAIN_ID)
)ENGINE = InnoDB;

#------------------------------------------------------------------------------------------------
#-- Table REF_COUNTRY_CODE
#------------------------------------------------------------------------------------------------

DROP TABLE IF EXISTS `REF_COUNTRY_CODE`;

CREATE TABLE IF NOT EXISTS `REF_COUNTRY_CODE`(
COUNTRY_ID INT NOT NULL,
COUNTRY_CURRENCY CHAR(3) NOT NULL,
COUNTRY_NAME VARCHAR(40) NOT NULL,
STANDARD_EXCHG_RATE DECIMAL(6,3) NOT NULL,
PRIMARY KEY (COUNTRY_ID)
)ENGINE = InnoDB;

#------------------------------------------------------------------------------------------------
#-- Table HOTELS
#------------------------------------------------------------------------------------------------

DROP TABLE IF EXISTS `HOTELS`;

CREATE TABLE IF NOT EXISTS `HOTELS`(
HOTEL_ID INT NOT NULL,
HOTEL_CHAINS_HOTEL_CHAIN_ID INT NOT NULL,
REF_COUNTRY_CODE_COUNTRY_ID INT NOT NULL,
HOTEL_NAME VARCHAR(100) NULL,
EMAIL_ADDRESS VARCHAR(100) NULL,
HOTEL_ADDRESS VARCHAR(150) NULL,
HOTEL_URL VARCHAR(150) NULL,
HOTEL_CONTACT_NUMBER VARCHAR(12) NULL,
PRIMARY KEY (HOTEL_ID),
CONSTRAINT HOTELS_HOTEL_CHAINS
	FOREIGN KEY (HOTEL_CHAINS_HOTEL_CHAIN_ID) 
	REFERENCES `HOTEL_CHAINS`(HOTEL_CHAIN_ID)
	ON DELETE CASCADE
    ON UPDATE RESTRICT,
CONSTRAINT HOTELS_REF_COUNTRY_CODE
	FOREIGN KEY (REF_COUNTRY_CODE_COUNTRY_ID) 
	REFERENCES `REF_COUNTRY_CODE`(COUNTRY_ID)
	ON DELETE CASCADE
    ON UPDATE RESTRICT
) ENGINE = InnoDB;

CREATE INDEX `FK_HOTELS_HOTEL_CHAINS_IDX` ON `HOTELS` (HOTEL_CHAINS_HOTEL_CHAIN_ID ASC);

CREATE INDEX `FK_HOTELS_REF_COUNTRY_CODE_IDX` ON `HOTELS` (REF_COUNTRY_CODE_COUNTRY_ID ASC);


#------------------------------------------------------------------------------------------------
#-- Table ROOM_TYPE
#------------------------------------------------------------------------------------------------
DROP TABLE IF EXISTS `ROOM_TYPE`;

CREATE TABLE IF NOT EXISTS `ROOM_TYPE`(
ROOM_TYPE_ID INT NOT NULL,
ROOM_TYPE_NAME VARCHAR(45) NULL,
ROOM_COST DECIMAL(10,2) NULL,
ROOM_TYPE_DESCRIPTION VARCHAR(100),
SMOKE_FRIENDLY TINYINT(1) NULL,
PET_FRIENDLY TINYINT(1) NULL,
PRIMARY KEY(ROOM_TYPE_ID)
) ENGINE = InnoDB;

#------------------------------------------------------------------------------------------------
#-- Table ROOMS
#------------------------------------------------------------------------------------------------
DROP TABLE IF EXISTS `ROOMS`;

CREATE TABLE IF NOT EXISTS `ROOMS`(
ROOM_ID INT NOT NULL,
ROOM_TYPE_ROOM_TYPE_ID INT NOT NULL,
HOTELS_HOTEL_ID INT NOT NULL,
PRIMARY KEY (ROOM_ID, ROOM_TYPE_ROOM_TYPE_ID, HOTELS_HOTEL_ID),
CONSTRAINT `FK_ROOMS_ROOM_TYPE`
	FOREIGN KEY (ROOM_TYPE_ROOM_TYPE_ID)
	REFERENCES `ROOM_TYPE`(ROOM_TYPE_ID)
	ON DELETE CASCADE
    ON UPDATE RESTRICT,
CONSTRAINT `FK_ROOMS_HOTELS`
	FOREIGN KEY (HOTELS_HOTEL_ID)
	REFERENCES `HOTELS`(HOTEL_ID)
	ON DELETE CASCADE
    ON UPDATE RESTRICT
) ENGINE = InnoDB;

CREATE INDEX `FK_ROOMS_ROOM_TYPE_IDX` ON `ROOMS` (ROOM_TYPE_ROOM_TYPE_ID ASC);

CREATE INDEX `FK_ROOMS_HOTELS_IDX` ON `ROOMS` (HOTELS_HOTEL_ID ASC);

#------------------------------------------------------------------------------------------------
#-- Table GUESTS
#------------------------------------------------------------------------------------------------
DROP TABLE IF EXISTS `GUESTS`;

CREATE TABLE IF NOT EXISTS `GUESTS`(
GUEST_ID INT NOT NULL,
GUEST_FIRST_NAME VARCHAR(45) NULL,
GUEST_LAST_NAME VARCHAR(45) NULL,
GUEST_CONTACT_NUMBER VARCHAR(12) NULL,
GUEST_EMAIL_ADDRESS VARCHAR(45) NULL,
PRIMARY KEY(GUEST_ID)
) ENGINE = InnoDB;

#------------------------------------------------------------------------------------------------
#-- Table BOOKINGS
#------------------------------------------------------------------------------------------------

DROP TABLE IF EXISTS `BOOKINGS`;

CREATE TABLE IF NOT EXISTS `BOOKINGS`(
BOOKING_ID INT NOT NULL,
ROOMS_ROOM_ID INT NOT NULL,
BOOKING_DATE DATETIME NULL,
DURATION_OF_STAY INT NULL,
CHECK_IN_DATE DATETIME NULL,
CHECK_OUT_DATE DATETIME NULL,
BOOKING_PAYMENT_TYPE VARCHAR(45) NULL,
TOTAL_ROOMS_BOOKED INT NULL,
GUESTS_GUEST_ID INT NOT NULL,
PRIMARY KEY (BOOKING_ID, GUESTS_GUEST_ID, ROOMS_ROOM_ID),

CONSTRAINT `FK_BOOKINGS_ROOMS`
	FOREIGN KEY(ROOMS_ROOM_ID)
	REFERENCES `ROOMS`(ROOM_ID)
	ON DELETE CASCADE
    ON UPDATE RESTRICT,
CONSTRAINT `FK_BOOKINGS_GUESTS`
	FOREIGN KEY(GUESTS_GUEST_ID)
	REFERENCES `GUESTS`(GUEST_ID)
	ON DELETE CASCADE
    ON UPDATE RESTRICT
) ENGINE = InnoDB;

CREATE INDEX `FK_BOOKINGS_ROOMS_IDX` ON `BOOKINGS` (ROOMS_ROOM_ID ASC);

CREATE INDEX `FK_BOOKINGS_GUESTS_IDX` ON `BOOKINGS` (GUESTS_GUEST_ID ASC);

