# Query to generate final report
SELECT HOTEL_CHAINS.HOTEL_CHAIN_ID, HOTEL_CHAINS.HOTEL_CHAIN_NAME, 
SUM(ROOM_TYPE.ROOM_COST * (DATEDIFF(CONVERT(BOOKINGS.CHECK_OUT_DATE, DATE), CONVERT(BOOKINGS.CHECK_IN_DATE, DATE))) * BOOKINGS.TOTAL_ROOMS_BOOKED) AS REVENUE
FROM
HOTEL_CHAINS JOIN HOTELS ON HOTEL_CHAINS.HOTEL_CHAIN_ID = HOTELS.HOTEL_CHAINS_HOTEL_CHAIN_ID
				 JOIN ROOMS ON HOTELS.HOTEL_ID = ROOMS.HOTELS_HOTEL_ID
				 JOIN ROOM_TYPE ON ROOMS.ROOM_TYPE_ROOM_TYPE_ID = ROOM_TYPE.ROOM_TYPE_ID
				 JOIN BOOKINGS ON ROOMS.ROOM_ID = BOOKINGS.ROOMS_ROOM_ID
GROUP BY HOTEL_CHAINS.HOTEL_CHAIN_ID, HOTEL_CHAINS.HOTEL_CHAIN_NAME
ORDER BY HOTEL_CHAINS.HOTEL_CHAIN_ID;				 


# UNION Query to test our report (Result for both should match to ensure our report is correct)
SELECT HOTEL_CHAINS.HOTEL_CHAIN_ID, HOTEL_CHAINS.HOTEL_CHAIN_NAME, 
SUM(ROOM_TYPE.ROOM_COST * (DATEDIFF(CONVERT(BOOKINGS.CHECK_OUT_DATE, DATE), CONVERT(BOOKINGS.CHECK_IN_DATE, DATE))) * BOOKINGS.TOTAL_ROOMS_BOOKED) AS REVENUE_HOTEL_CHAIN
FROM
HOTEL_CHAINS JOIN HOTELS ON HOTEL_CHAINS.HOTEL_CHAIN_ID = HOTELS.HOTEL_CHAINS_HOTEL_CHAIN_ID
				 JOIN ROOMS ON HOTELS.HOTEL_ID = ROOMS.HOTELS_HOTEL_ID
				 JOIN ROOM_TYPE ON ROOMS.ROOM_TYPE_ROOM_TYPE_ID = ROOM_TYPE.ROOM_TYPE_ID
				 JOIN BOOKINGS ON ROOMS.ROOM_ID = BOOKINGS.ROOMS_ROOM_ID
WHERE HOTEL_CHAINS.HOTEL_CHAIN_ID = 1
GROUP BY HOTEL_CHAINS.HOTEL_CHAIN_ID, HOTEL_CHAINS.HOTEL_CHAIN_NAME

UNION

SELECT HOTEL_CHAINS.HOTEL_CHAIN_ID, HOTEL_CHAINS.HOTEL_CHAIN_NAME, 
SUM(ROOM_TYPE.ROOM_COST * (DATEDIFF(CONVERT(BOOKINGS.CHECK_OUT_DATE, DATE), CONVERT(BOOKINGS.CHECK_IN_DATE, DATE))) * BOOKINGS.TOTAL_ROOMS_BOOKED) AS REVENUE_HOTEL_CHAIN
FROM
HOTEL_CHAINS JOIN HOTELS ON HOTEL_CHAINS.HOTEL_CHAIN_ID = HOTELS.HOTEL_CHAINS_HOTEL_CHAIN_ID
				 JOIN ROOMS ON HOTELS.HOTEL_ID = ROOMS.HOTELS_HOTEL_ID
				 JOIN ROOM_TYPE ON ROOMS.ROOM_TYPE_ROOM_TYPE_ID = ROOM_TYPE.ROOM_TYPE_ID
				 JOIN BOOKINGS ON ROOMS.ROOM_ID = BOOKINGS.ROOMS_ROOM_ID
WHERE HOTEL_CHAINS.HOTEL_CHAIN_ID = 2
GROUP BY HOTEL_CHAINS.HOTEL_CHAIN_ID, HOTEL_CHAINS.HOTEL_CHAIN_NAME

UNION

SELECT HOTEL_CHAINS.HOTEL_CHAIN_ID, HOTEL_CHAINS.HOTEL_CHAIN_NAME, 
SUM(ROOM_TYPE.ROOM_COST * (DATEDIFF(CONVERT(BOOKINGS.CHECK_OUT_DATE, DATE), CONVERT(BOOKINGS.CHECK_IN_DATE, DATE))) * BOOKINGS.TOTAL_ROOMS_BOOKED) AS REVENUE_HOTEL_CHAIN
FROM
HOTEL_CHAINS JOIN HOTELS ON HOTEL_CHAINS.HOTEL_CHAIN_ID = HOTELS.HOTEL_CHAINS_HOTEL_CHAIN_ID
				 JOIN ROOMS ON HOTELS.HOTEL_ID = ROOMS.HOTELS_HOTEL_ID
				 JOIN ROOM_TYPE ON ROOMS.ROOM_TYPE_ROOM_TYPE_ID = ROOM_TYPE.ROOM_TYPE_ID
				 JOIN BOOKINGS ON ROOMS.ROOM_ID = BOOKINGS.ROOMS_ROOM_ID
WHERE HOTEL_CHAINS.HOTEL_CHAIN_ID = 3
GROUP BY HOTEL_CHAINS.HOTEL_CHAIN_ID, HOTEL_CHAINS.HOTEL_CHAIN_NAME

UNION

SELECT HOTEL_CHAINS.HOTEL_CHAIN_ID, HOTEL_CHAINS.HOTEL_CHAIN_NAME, 
SUM(ROOM_TYPE.ROOM_COST * (DATEDIFF(CONVERT(BOOKINGS.CHECK_OUT_DATE, DATE), CONVERT(BOOKINGS.CHECK_IN_DATE, DATE))) * BOOKINGS.TOTAL_ROOMS_BOOKED) AS REVENUE_HOTEL_CHAIN
FROM
HOTEL_CHAINS JOIN HOTELS ON HOTEL_CHAINS.HOTEL_CHAIN_ID = HOTELS.HOTEL_CHAINS_HOTEL_CHAIN_ID
				 JOIN ROOMS ON HOTELS.HOTEL_ID = ROOMS.HOTELS_HOTEL_ID
				 JOIN ROOM_TYPE ON ROOMS.ROOM_TYPE_ROOM_TYPE_ID = ROOM_TYPE.ROOM_TYPE_ID
				 JOIN BOOKINGS ON ROOMS.ROOM_ID = BOOKINGS.ROOMS_ROOM_ID
WHERE HOTEL_CHAINS.HOTEL_CHAIN_ID = 4
GROUP BY HOTEL_CHAINS.HOTEL_CHAIN_ID, HOTEL_CHAINS.HOTEL_CHAIN_NAME

UNION

SELECT HOTEL_CHAINS.HOTEL_CHAIN_ID, HOTEL_CHAINS.HOTEL_CHAIN_NAME, 
SUM(ROOM_TYPE.ROOM_COST * (DATEDIFF(CONVERT(BOOKINGS.CHECK_OUT_DATE, DATE), CONVERT(BOOKINGS.CHECK_IN_DATE, DATE))) * BOOKINGS.TOTAL_ROOMS_BOOKED) AS REVENUE_HOTEL_CHAIN
FROM
HOTEL_CHAINS JOIN HOTELS ON HOTEL_CHAINS.HOTEL_CHAIN_ID = HOTELS.HOTEL_CHAINS_HOTEL_CHAIN_ID
				 JOIN ROOMS ON HOTELS.HOTEL_ID = ROOMS.HOTELS_HOTEL_ID
				 JOIN ROOM_TYPE ON ROOMS.ROOM_TYPE_ROOM_TYPE_ID = ROOM_TYPE.ROOM_TYPE_ID
				 JOIN BOOKINGS ON ROOMS.ROOM_ID = BOOKINGS.ROOMS_ROOM_ID
WHERE HOTEL_CHAINS.HOTEL_CHAIN_ID = 5
GROUP BY HOTEL_CHAINS.HOTEL_CHAIN_ID, HOTEL_CHAINS.HOTEL_CHAIN_NAME;